#!/usr/bin/ruby

require 'rubygems'
require 'optparse'

require 'lib/rumplayer'
$options = {}

OptionParser.new do |opts|
  opts.banner = "RuMplayer - play common movies synchronously"
  opts.banner = "Usage: #{$0} [options]"

  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    $options[:verbose] = v
  end

end.parse!

include Rumplayer
if ARGV.empty?
  Client.wait
else
  Client.run(ARGV)
end

