#!/usr/bin/ruby

require 'rubygems'
require 'optparse'

require 'active_support'

APP_ROOT = File.expand_path( File.dirname(__FILE__) )
ActiveSupport::Dependencies::load_paths << File.join(APP_ROOT, "lib")


$options = {}

OptionParser.new do |opts|
  opts.banner = <<-EOTEXT
RuMplayer - play common movies synchronously

Usage: #{$0} [options] [file(s)]
  #{$0}  (no files)            start and listen for commands
  #{$0}  one or more files     start distributed playback

Hint: All watchers must start this command from the same directory,
      all paths are relative
  EOTEXT

  opts.separator ''
  opts.separator "Options:"
  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    $options[:verbose] = v
  end

  opts.on("-s", "--server", "Start Server on configured uri") do |s|
    $options[:server] = s
  end


end.parse!

if $options[:server]
  Rumplayer::Server.start
else
  if ARGV.empty?
    Rumplayer::Client.wait
  else
    Rumplayer::Client.run(ARGV)
  end
end

