# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rumplayer}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Niklas Hofer"]
  s.date = %q{2009-12-15}
  s.default_executable = %q{rumplayer}
  s.description = %q{
      RumPlayer allows you and your buddies to watch movies simultaneously
      without sharing the room or continent. All participans must have a copy
      of the movie to watch.
    }
  s.email = %q{niklas+rumplayer@lanpartei.de}
  s.executables = ["rumplayer"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Rakefile",
     "lib/drbfire.rb",
     "lib/rumplayer.rb",
     "lib/rumplayer/client.rb",
     "lib/rumplayer/config.rb",
     "lib/rumplayer/mplayer.rb",
     "lib/rumplayer/server.rb"
  ]
  s.homepage = %q{http://github.com/niklas/rumplayer/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{watch common movies simultaneously}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

